{% set name = "cppzmq" %}
{% set version = "4.10.0" %}
{% set sha256 = "c81c81bba8a7644c84932225f018b5088743a22999c6d82a2b5f5cd1e6942b74" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/zeromq/cppzmq/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('cxx') }}
  host:
    - zeromq

test:
  commands:
    - test -f ${PREFIX}/share/cmake/cppzmq/cppzmqConfig.cmake         # [unix]
    - test -f ${PREFIX}/share/cmake/cppzmq/cppzmqConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\share\cmake\cppzmq\cppzmqConfig.cmake (exit 0) else (exit 1)         # [win]
    - if exist %LIBRARY_PREFIX%\share\cmake\cppzmq\cppzmqConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://zeromq.org
  license: MIT
  license_file: LICENSE
  summary: C++ bindings for 0MQ

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
