{% set name = "cppzmq" %}
{% set version = "4.4.0" %}
{% set sha256 = "118b9ff117f07d1aabadfb905d7227362049d7940d16b7863b3dd3cebd28be85" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/zeromq/cppzmq/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    - zeromq >=4.2.3,<4.4.0

  run:
    - {{ pin_compatible('zeromq', max_pin='x.x') }}

test:
  commands:
    - test -f ${PREFIX}/share/cmake/cppzmq/cppzmqConfig.cmake         # [unix]
    - test -f ${PREFIX}/share/cmake/cppzmq/cppzmqConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\share\cmake\cppzmq\cppzmqConfig.cmake (exit 0) else (exit 1)         # [win]
    - if exist %LIBRARY_PREFIX%\share\cmake\cppzmq\cppzmqConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://zeromq.org
  license: MIT
  summary: C++ bindings for 0MQ

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
