{% set name = "cppzmq" %}
{% set version = "4.9.0" %}
{% set sha256 = "3fdf5b100206953f674c94d40599bdb3ea255244dcc42fab0d75855ee3645581" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/zeromq/cppzmq/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('cxx') }}
  host:
    - zeromq

test:
  commands:
    - test -f ${PREFIX}/share/cmake/cppzmq/cppzmqConfig.cmake         # [unix]
    - test -f ${PREFIX}/share/cmake/cppzmq/cppzmqConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\share\cmake\cppzmq\cppzmqConfig.cmake (exit 0) else (exit 1)         # [win]
    - if exist %LIBRARY_PREFIX%\share\cmake\cppzmq\cppzmqConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://zeromq.org
  license: MIT
  license_file: LICENSE
  summary: C++ bindings for 0MQ

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
